# ~/.config/starship.toml

format = """
$username\
$hostname\
$shlvl\
$singularity\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$cmake\
$golang\
$helm\
$lua\
$pulumi\
$python\
$rust\
$terraform\
$nix_shell\
$memory_usage\
$aws\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character
"""
# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

